-- Question 1
SELECT STAND_NAME, UPPER(STAND_NAME) AS STAND_UPPER, LOWER(STAND_NAME) AS STAND_LOWER, INITCAP(STAND_NAME) AS STAND_TITLE
FROM STAND_USER;


-- Question 2
SELECT USER_NAME, CATCHPHRASE,LENGTH(CATCHPHRASE) AS PHRASE_LENGTH
FROM STAND_USER
ORDER BY PHRASE_LENGTH DESC;


-- Question 3
SELECT STAND_NAME,SUBSTR(STAND_NAME, 1, 8) AS STAND_SHORT
FROM STAND_USER;


-- Question 4
SELECT STAND_NAME,INSTR(STAND_NAME, 'World') AS WORLD_POSITION
FROM STAND_USER;


-- Question 5
SELECT USER_NAME,POWER,LPAD(TO_CHAR(POWER), 8, '#') AS PADDED_POWER
FROM STAND_USER;


-- Question 6
SELECT USER_NAME,POWER,ROUND(POWER, -2) AS ROUNDED_POWER,TRUNC(POWER, -2) AS TRUNCATED_POWER,MOD(POWER, 300) AS POWER_MOD_300
FROM STAND_USER;


-- Question 7
SELECT USER_NAME,NVL(TO_CHAR(PRECISION), 'Unknown') AS PRECISION_STATUS
FROM STAND_USER;


-- Question 8
SELECT USER_NAME,DEBUT_DATE,NEXT_DAY(ADD_MONTHS(DEBUT_DATE, 6), 'MONDAY') AS TRAINING_REVIEW
FROM STAND_USER;


-- Question 9
SELECT USER_NAME,ROUND(MONTHS_BETWEEN(SYSDATE, DEBUT_DATE)) AS MONTHS_SINCE_DEBUT
FROM STAND_USER
ORDER BY MONTHS_SINCE_DEBUT DESC;

-- Question 11
SELECT STAND_NAME
FROM STAND_USER
WHERE REGEXP_LIKE(STAND_NAME, 'world', 'i');


-- Question 12
SELECT USER_NAME,STAND_NAME,SOUNDEX(STAND_NAME) AS SOUND_GROUP
FROM STAND_USER
ORDER BY SOUND_GROUP;
